name: docs
channels:
  - conda-forge
  dependencies:
  - pip==22.1.1
  - pip:
    - aepsych==0.2.0
    - aepsych-client==0.1.1
    - bqplot
    - ipympl
    - ipyvolume
    - scipy
    - voila==0.2.16
    - ipywidgets==7.6.5
    - IPython==7.31.1
    - jupyterlab==3.4.4
    - notebook==6.4.12
