dependencies:
  - python==3.9.4
  - pip==22.1.1
  - pip:
    - aepsych==0.2.0
    - aepsych-client==0.1.1
    - bqplot
    - ipympl
    - ipyvolume
    - scipy
    - viola==0.3.8
    - ipywidgets==7.5.0
    - jupyterlab>=3.1
