dependencies:
  - python==3.9.4
  - pip==22.1.1
  - pip:
    - aepsych==0.2.0
    - aepsych-client==0.1.1
    - bqplot
    - ipympl
    - ipyvolume
    - scipy
    - voila==0.2.16
    - ipywidgets==7.7.1
    # - jupyterlab>=3.1
    - ipython==8.4.0
    - jupyter-client==6.1.12
    - jupyter-core==4.10.0
    - jupyter-dashboards==0.7.0
    - jupyter-declarativewidgets==0.7.0
    - jupyter-server==1.18.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.0
    - jupyterlab-widgets==1.1.1
    - matplotlib==3.5.2
