name: voila-gallery-country-indicators
channels:
- conda-forge
dependencies:
- matplotlib-base
- pandas
- ipywidgets
- jupyterlab>=3.1
- voila>=0.2.11
- aepsych==0.2.0
- aepsych-client==0.1.1
- ipywidgets==7.7.1


#     - bqplot
#     - ipympl
#     - ipyvolume
#     - scipy
#     - voila
#     - ipywidgets==7.7.1
#     - jupyterlab==3


# dependencies:
#   - python==3.9.4
#   - pip==22.1.1
#   - pip:
#     - aepsych==0.2.0
#     - aepsych-client==0.1.1
#     - bqplot
#     - ipympl
#     - ipyvolume
#     - scipy
#     - voila
#     - panel
#     - ipywidgets==7.7.1
#     - jupyterlab==3
